import QtQuick
import Quickshell
import Quickshell.Io
import "../common"

// Carries the shell's palette and mode to the rest of the system. Every
// time they change (or the wallpaper's colors do), it rewrites:
//  - dconf: color-scheme (what the portal publishes and Firefox, Chrome,
//    GTK4, Qt and kitty follow), gtk-theme and icon-theme (GTK3 apps).
//  - GTK3: its own theme (~/.local/share/themes/spore-{a,b}) that imports
//    adw-gtk3(-dark) and thunar.css and defines libadwaita's colors; GTK3
//    reloads it live when gtk-theme changes (see the script).
//  - GTK4: ~/.config/gtk-4.0/gtk.css with the same colors (on reopen).
//  - kitty: $XDG_STATE_HOME/spore/kitty-{dark,light}.conf, linked as
//    ~/.config/kitty/*-theme.auto.conf; kitty picks one by color-scheme
//    and SIGUSR1 makes it re-read them.
//  - niri: focus-ring and border colors in $XDG_STATE_HOME/spore/niri.kdl,
//    which the user's niri config includes.
//  - rofi: color variables in $XDG_STATE_HOME/spore/rofi-colors.rasi,
//    which the user's rofi theme imports.
//  - yazi: $XDG_STATE_HOME/spore/yazi-theme.toml, linked as
//    ~/.config/yazi/theme.toml (when yazi opens).
//  - zed: $XDG_STATE_HOME/spore/zed-theme.json (dark and light variants),
//    linked as ~/.config/zed/themes/spore.json.
//  - Kate/KDE: the [Colors:*] groups of ~/.config/kdeglobals and the
//    editor theme in ~/.config/katerc. Kate only picks them up on reopen.
//
// dconf rather than gsettings: on NixOS the schemas aren't in XDG_DATA_DIRS
// and gsettings fails with "No schemas installed".
Scope {
    id: root

    required property Theme theme
    // shell.qml sets it to true once it has read mode and palette from disk:
    // before that it would write the defaults over what was chosen.
    property bool ready: false
    // false in a nested test niri (Compositor.nested): dconf, the GTK themes,
    // kdeglobals, kitty and the state files are the real session's, and the
    // test overwrote them with its colors.
    property bool enabled: true
    Component.onCompleted: Qt.callLater(() => { if (!enabled) console.info("SystemTheme: disabled (nested compositor)") })

    readonly property string stateDir: (Quickshell.env("XDG_STATE_HOME") || Quickshell.env("HOME") + "/.local/state") + "/spore"

    // Changes with anything that affects the generated output.
    readonly property string signature: JSON.stringify([
        theme.palette, theme.mode, theme.colorsFor(theme.palette, "dark"), theme.colorsFor(theme.palette, "light")])

    onSignatureChanged: if (ready && enabled) debounce.restart()
    onReadyChanged: if (ready && enabled) debounce.restart()

    // At startup mode, palette and colors.json arrive almost together: write
    // once, with the final state.
    Timer {
        id: debounce
        interval: 300
        onTriggered: if (root.enabled) root.apply()
    }

    function hexToRgb(h: string): var {
        h = h.replace("#", "")
        return [0, 2, 4].map(i => parseInt(h.substr(i, 2), 16))
    }

    function rgbToHex(c: var): string {
        return "#" + c.map(v => Math.round(v).toString(16).padStart(2, "0")).join("")
    }

    // t = 0 -> a, t = 1 -> b.
    function mix(a: string, b: string, t: real): string {
        const x = hexToRgb(a), y = hexToRgb(b)
        return rgbToHex(x.map((v, i) => v + (y[i] - v) * t))
    }

    function colors(m: string): var {
        return theme.colorsFor(theme.palette, m) || theme.palettes.catppuccin[m]
    }

    function gtkCss(c: var): string {
        const d = (name, value) => "@define-color " + name + " " + value + ";"
        return [
            "/* Generated by spore (shell/services/SystemTheme.qml): rewritten when the palette or mode changes. */",
            d("accent_color", c.accent),
            d("accent_bg_color", c.accent),
            d("accent_fg_color", c.textOnAccent),
            d("window_bg_color", c.base),
            d("window_fg_color", c.text),
            d("view_bg_color", c.base),
            d("view_fg_color", c.text),
            d("headerbar_bg_color", c.base),
            d("headerbar_fg_color", c.text),
            d("headerbar_backdrop_color", c.base),
            d("sidebar_bg_color", c.base),
            d("sidebar_fg_color", c.text),
            d("sidebar_backdrop_color", c.base),
            d("sidebar_border_color", c.base),
            d("card_bg_color", mix(c.base, c.text, 0.05)),
            d("card_fg_color", c.text),
            d("popover_bg_color", mix(c.base, c.text, 0.03)),
            d("popover_fg_color", c.text),
            d("dialog_bg_color", c.base),
            d("dialog_fg_color", c.text),
            d("destructive_color", c.error),
            d("destructive_bg_color", c.error),
            d("destructive_fg_color", c.base),
            d("error_color", c.error),
            // Old GTK3 names that adw-gtk3 still uses for the selection.
            d("theme_selected_bg_color", c.accent),
            d("theme_selected_fg_color", c.textOnAccent),
            ""
        ].join("\n")
    }

    function kittyConf(c: var): string {
        const lines = [
            "# Generated by spore (shell/services/SystemTheme.qml): rewritten when the palette or mode changes.",
            "background " + c.base,
            "foreground " + c.text,
            "cursor " + c.accent,
            "cursor_text_color " + c.base,
            "selection_background " + c.surface,
            "selection_foreground " + c.text,
            "url_color " + c.accent,
            "active_border_color " + c.accent,
            "inactive_border_color " + c.surface,
            "active_tab_background " + c.accent,
            "active_tab_foreground " + c.textOnAccent,
            "inactive_tab_background " + c.crust,
            "inactive_tab_foreground " + c.text,
            "tab_bar_background " + c.crust
        ]
        c.ansi.forEach((v, i) => lines.push("color" + i + " " + v))
        return lines.join("\n") + "\n"
    }

    // Border only, the same width on every window: the active one with the
    // accent and the rest gray. The focus-ring is off because it's drawn
    // outside the border and the active window ended up twice as thick. The
    // width stays in config.kdl; this only overrides colors and on/off.
    function niriColors(c: var): string {
        return [
            "// Generated by spore (shell/services/SystemTheme.qml): rewritten when the palette or mode changes.",
            "// Included by the niri config (include optional=true \"~/.local/state/spore/niri.kdl\").",
            "layout {",
            "    focus-ring {",
            "        off",
            "    }",
            "    border {",
            "        on",
            "        active-color \"" + c.accent + "\"",
            "        inactive-color \"" + mix(c.base, c.text, 0.3) + "\"",
            "        urgent-color \"" + c.error + "\"",
            "    }",
            "}",
            ""
        ].join("\n")
    }

    // yazi's theme.toml (not flavors: yazi 26.9 ignored them in testing, while
    // colors set directly in theme.toml do apply). It only overrides what the
    // default theme has with fixed colors or with the terminal's "blue" as the
    // accent (borders, tabs, mode, selected row...); icons and file types stay
    // as in yazi's theme, which uses the terminal colors, and those already
    // follow the palette through kitty.
    function yaziTheme(c: var): string {
        const s = (fg, bg, extra) => "{ " + [fg ? "fg = \"" + fg + "\"" : "", bg ? "bg = \"" + bg + "\"" : "", extra || ""]
            .filter(x => x).join(", ") + " }"
        const muted = mix(c.text, c.base, 0.45)
        const border = s(c.accent)
        return [
            "# Generated by spore (shell/services/SystemTheme.qml): rewritten when the palette or mode changes.",
            "# ~/.config/yazi/theme.toml is a symlink to this file.",
            "[mgr]",
            "cwd             = " + s(c.accent),
            "find_keyword    = " + s(c.ansi[3], "", "bold = true, italic = true, underline = true"),
            "find_position   = " + s(c.ansi[5], "", "bold = true, italic = true"),
            "marker_copied   = " + s(c.ansi[2], c.ansi[2]),
            "marker_cut      = " + s(c.error, c.error),
            "marker_marked   = " + s(c.ansi[6], c.ansi[6]),
            "marker_selected = " + s(c.accent, c.accent),
            "count_copied    = " + s(c.base, c.ansi[2]),
            "count_cut       = " + s(c.base, c.error),
            "count_selected  = " + s(c.textOnAccent, c.accent),
            "border_style    = " + s(muted),
            "",
            "[tabs]",
            "active   = " + s(c.textOnAccent, c.accent, "bold = true"),
            "inactive = " + s(c.accent, c.surface),
            "",
            "[mode]",
            "normal_main = " + s(c.textOnAccent, c.accent, "bold = true"),
            "normal_alt  = " + s(c.accent, c.surface),
            "select_main = " + s(c.base, c.ansi[5], "bold = true"),
            "select_alt  = " + s(c.ansi[5], c.surface),
            "unset_main  = " + s(c.base, c.error, "bold = true"),
            "unset_alt   = " + s(c.error, c.surface),
            "",
            "[indicator]",
            "parent  = " + s(c.text, c.surface),
            "current = " + s(c.textOnAccent, c.accent),
            "preview = " + s("", "", "underline = true"),
            "",
            "[status]",
            "perm_sep        = " + s(muted),
            "perm_type       = " + s(c.ansi[2]),
            "perm_read       = " + s(c.ansi[3]),
            "perm_write      = " + s(c.error),
            "perm_exec       = " + s(c.ansi[6]),
            "progress_normal = " + s(c.accent, c.surface),
            "progress_error  = " + s(c.error, c.surface),
            "",
            "[which]",
            "border          = " + border,
            "cand            = " + s(c.accent),
            "rest            = " + s(muted),
            "desc            = " + s(c.ansi[5]),
            "separator_style = " + s(muted),
            "",
            "[confirm]",
            "border = " + border,
            "title  = " + border,
            "",
            "[spot]",
            "border  = " + border,
            "title   = " + border,
            "tbl_col = " + border,
            "",
            "[notify]",
            "title_info  = " + s(c.ansi[2]),
            "title_warn  = " + s(c.ansi[3]),
            "title_error = " + s(c.error),
            "",
            "[pick]",
            "border = " + border,
            "active = " + s(c.accent, "", "bold = true"),
            "",
            "[input]",
            "border = " + border,
            "",
            "[cmp]",
            "border = " + border,
            "",
            "[tasks]",
            "border  = " + border,
            "hovered = " + s(c.accent, "", "bold = true"),
            "",
            "[help]",
            "border  = " + border,
            "chord   = " + s(c.accent),
            "hovered = " + s(c.textOnAccent, c.accent, "bold = true"),
            ""
        ].join("\n")
    }

    // Zed theme (schema v0.2.0) with both variants of the palette: Zed picks
    // "Spore Dark" or "Spore Light" by the system's mode (theme.mode = "system"
    // in the user's Zed settings.json). Syntax uses the palette's terminal
    // colors (matches kitty) and the accent for keywords, focus, cursor and
    // selection.
    function zedTheme(dark: var, light: var): string {
        const a = (hex, alpha) => hex + alpha
        const variant = (name, appearance, c) => {
            const muted = mix(c.text, c.base, 0.35)
            const faint = mix(c.text, c.base, 0.5)
            const chrome = c.crust
            const hover = mix(c.base, c.text, 0.08)
            const selected = mix(c.base, c.accent, 0.25)
            const border = mix(c.base, c.text, 0.12)
            const ansi = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
            const style = {
                "background": chrome,
                "surface.background": chrome,
                "elevated_surface.background": mix(c.base, c.text, 0.05),
                "drop_target.background": a(c.accent, "30"),
                "border": border,
                "border.variant": mix(c.base, c.text, 0.08),
                "border.focused": c.accent,
                "border.selected": c.accent,
                "border.transparent": "#00000000",
                "border.disabled": border,
                "pane.focused_border": c.accent,
                "panel.focused_border": c.accent,
                "element.background": c.surface,
                "element.hover": hover,
                "element.active": selected,
                "element.selected": selected,
                "element.disabled": c.surface,
                "ghost_element.background": "#00000000",
                "ghost_element.hover": hover,
                "ghost_element.active": selected,
                "ghost_element.selected": selected,
                "ghost_element.disabled": "#00000000",
                "text": c.text,
                "text.muted": muted,
                "text.placeholder": faint,
                "text.disabled": faint,
                "text.accent": c.accent,
                "icon": c.text,
                "icon.muted": muted,
                "icon.disabled": faint,
                "icon.placeholder": faint,
                "icon.accent": c.accent,
                "link_text.hover": c.accent,
                "title_bar.background": chrome,
                "title_bar.inactive_background": chrome,
                "toolbar.background": c.base,
                "tab_bar.background": chrome,
                "tab.inactive_background": chrome,
                "tab.active_background": c.base,
                "status_bar.background": chrome,
                "panel.background": chrome,
                "editor.background": c.base,
                "editor.foreground": c.text,
                "editor.gutter.background": c.base,
                "editor.subheader.background": chrome,
                "editor.active_line.background": mix(c.base, c.text, 0.05),
                "editor.highlighted_line.background": mix(c.base, c.text, 0.05),
                "editor.line_number": faint,
                "editor.active_line_number": c.accent,
                "editor.invisible": mix(c.text, c.base, 0.7),
                "editor.wrap_guide": mix(c.base, c.text, 0.08),
                "editor.active_wrap_guide": mix(c.base, c.text, 0.15),
                "editor.document_highlight.read_background": a(c.accent, "20"),
                "editor.document_highlight.write_background": a(c.accent, "30"),
                "search.match_background": a(c.accent, "40"),
                "scrollbar.thumb.background": a(mix(c.base, c.text, 0.3), "80"),
                "scrollbar.thumb.hover_background": mix(c.base, c.text, 0.35),
                "scrollbar.thumb.border": "#00000000",
                "scrollbar.track.background": "#00000000",
                "scrollbar.track.border": "#00000000",
                "error": c.error, "error.background": a(c.error, "20"), "error.border": c.error,
                "warning": c.ansi[3], "warning.background": a(c.ansi[3], "20"), "warning.border": c.ansi[3],
                "success": c.ansi[2], "success.background": a(c.ansi[2], "20"), "success.border": c.ansi[2],
                "info": c.accent, "info.background": a(c.accent, "20"), "info.border": c.accent,
                "hint": muted, "hint.background": a(c.accent, "10"), "hint.border": muted,
                "created": c.ansi[2], "created.background": a(c.ansi[2], "20"), "created.border": c.ansi[2],
                "modified": c.ansi[3], "modified.background": a(c.ansi[3], "20"), "modified.border": c.ansi[3],
                "deleted": c.error, "deleted.background": a(c.error, "20"), "deleted.border": c.error,
                "conflict": c.ansi[5], "conflict.background": a(c.ansi[5], "20"), "conflict.border": c.ansi[5],
                "renamed": c.ansi[4], "renamed.background": a(c.ansi[4], "20"), "renamed.border": c.ansi[4],
                "ignored": faint, "ignored.background": "#00000000", "ignored.border": faint,
                "hidden": faint, "hidden.background": "#00000000", "hidden.border": faint,
                "predictive": faint, "predictive.background": "#00000000", "predictive.border": faint,
                "unreachable": faint, "unreachable.background": "#00000000", "unreachable.border": faint,
                "terminal.background": c.base,
                "terminal.foreground": c.text,
                "terminal.bright_foreground": c.text,
                "terminal.dim_foreground": muted,
                "players": [{ "cursor": c.accent, "background": c.accent, "selection": a(c.accent, "40") }],
                "syntax": {
                    "keyword": { "color": c.accent },
                    "preproc": { "color": c.accent },
                    "string": { "color": c.ansi[2] },
                    "string.escape": { "color": c.ansi[6] },
                    "string.regex": { "color": c.ansi[5] },
                    "string.special": { "color": c.ansi[6] },
                    "string.special.symbol": { "color": c.ansi[6] },
                    "comment": { "color": muted, "font_style": "italic" },
                    "comment.doc": { "color": muted, "font_style": "italic" },
                    "function": { "color": c.ansi[4] },
                    "function.method": { "color": c.ansi[4] },
                    "function.builtin": { "color": c.ansi[4] },
                    "function.definition": { "color": c.ansi[4] },
                    "constructor": { "color": c.ansi[6] },
                    "type": { "color": c.ansi[6] },
                    "type.builtin": { "color": c.ansi[6] },
                    "type.interface": { "color": c.ansi[6] },
                    "enum": { "color": c.ansi[6] },
                    "variant": { "color": c.ansi[3] },
                    "number": { "color": c.ansi[3] },
                    "boolean": { "color": c.ansi[3] },
                    "constant": { "color": c.ansi[3] },
                    "variable": { "color": c.text },
                    "variable.member": { "color": c.text },
                    "variable.parameter": { "color": c.text },
                    "variable.special": { "color": c.ansi[1] },
                    "property": { "color": c.ansi[4] },
                    "attribute": { "color": c.ansi[3] },
                    "label": { "color": c.ansi[5] },
                    "tag": { "color": c.ansi[1] },
                    "operator": { "color": mix(c.text, c.base, 0.2) },
                    "punctuation": { "color": mix(c.text, c.base, 0.25) },
                    "punctuation.bracket": { "color": mix(c.text, c.base, 0.25) },
                    "punctuation.delimiter": { "color": mix(c.text, c.base, 0.25) },
                    "punctuation.special": { "color": c.accent },
                    "punctuation.list_marker": { "color": c.accent },
                    "title": { "color": c.accent, "font_weight": 700 },
                    "emphasis": { "color": c.text, "font_style": "italic" },
                    "emphasis.strong": { "color": c.text, "font_weight": 700 },
                    "link_text": { "color": c.accent },
                    "link_uri": { "color": c.ansi[6] },
                    "text.literal": { "color": c.ansi[2] },
                    "embedded": { "color": c.text },
                    "hint": { "color": muted },
                    "predictive": { "color": faint, "font_style": "italic" },
                    "primary": { "color": c.text }
                }
            }
            ansi.forEach((n, i) => {
                style["terminal.ansi." + n] = c.ansi[i]
                style["terminal.ansi.bright_" + n] = c.ansi[i + 8]
            })
            return { "name": name, "appearance": appearance, "style": style }
        }
        return JSON.stringify({
            "$schema": "https://zed.dev/schema/themes/v0.2.0.json",
            "name": "Spore",
            "author": "spore (shell/services/SystemTheme.qml), rewritten when the palette or mode changes",
            "themes": [variant("Spore Dark", "dark", dark), variant("Spore Light", "light", light)]
        }, null, 2) + "\n"
    }

    // Only variables: the design lives in the user's rofi theme, which imports
    // this file.
    function rofiColors(c: var): string {
        return [
            "/* Generated by spore (shell/services/SystemTheme.qml): rewritten when the palette or mode changes. */",
            "/* Imported by the rofi theme (@import \"~/.local/state/spore/rofi-colors.rasi\"). */",
            "* {",
            "    bg:        " + c.base + ";",
            "    bg-alt:    " + mix(c.base, c.text, 0.08) + ";",
            "    fg:        " + c.text + ";",
            "    fg-muted:  " + mix(c.text, c.base, 0.45) + ";",
            "    accent:    " + c.accent + ";",
            "    on-accent: " + c.textOnAccent + ";",
            "}",
            ""
        ].join("\n")
    }

    // The same groups and keys as a KDE color scheme (.colors). If any is
    // missing, KColorScheme fills it in with light Breeze, so they're all here.
    function kdeColors(c: var, dark: bool): string {
        const rgb = h => hexToRgb(h).join(",")
        const group = (name, bg, alt, fg, active) => [
            "[Colors:" + name + "]",
            "BackgroundAlternate=" + rgb(alt),
            "BackgroundNormal=" + rgb(bg),
            "DecorationFocus=" + rgb(c.accent),
            "DecorationHover=" + rgb(c.accent),
            "ForegroundActive=" + rgb(active),
            "ForegroundInactive=" + rgb(mix(fg, bg, 0.4)),
            "ForegroundLink=" + rgb(active),
            "ForegroundNegative=" + rgb(c.error),
            "ForegroundNeutral=" + rgb(c.ansi[3]),
            "ForegroundNormal=" + rgb(fg),
            "ForegroundPositive=" + rgb(c.ansi[2]),
            "ForegroundVisited=" + rgb(mix(active, fg, 0.3)),
            ""
        ].join("\n")
        // In KDE the view (lists, the editor) is more sunken than the window in
        // dark mode and lighter in light mode, like Breeze.
        const view = dark ? c.crust : mix(c.base, "#ffffff", 0.6)
        const button = mix(c.base, c.text, 0.08)
        return [
            group("Window", c.base, mix(c.base, c.text, 0.05), c.text, c.accent),
            group("View", view, mix(view, c.text, 0.04), c.text, c.accent),
            group("Button", button, mix(button, c.text, 0.05), c.text, c.accent),
            group("Selection", c.accent, mix(c.accent, c.base, 0.3), c.textOnAccent, c.textOnAccent),
            group("Tooltip", c.crust, c.crust, c.text, c.accent),
            group("Header", c.crust, c.crust, c.text, c.accent),
            group("Header][Inactive", c.crust, c.crust, c.text, c.accent),
            group("Complementary", c.crust, c.crust, c.text, c.accent)
        ].join("\n")
    }

    function apply(): void {
        const dark = theme.mode === "dark"
        const c = colors(theme.mode)
        writer.command = ["sh", "-c", writer.script, "_",
            dark ? "prefer-dark" : "prefer-light",
            dark ? "adw-gtk3-dark" : "adw-gtk3",
            dark ? "Papirus-Dark" : "Papirus-Light",
            gtkCss(c),
            kittyConf(colors("dark")),
            kittyConf(colors("light")),
            kdeColors(c, dark),
            c.kate,
            root.stateDir,
            niriColors(c),
            rofiColors(c),
            yaziTheme(c),
            zedTheme(colors("dark"), colors("light"))]
        writer.running = true
    }

    Process {
        id: writer

        readonly property string script: `
            set -u
            scheme=$1 gtktheme=$2 icons=$3 gtkcss=$4 kittydark=$5 kittylight=$6 kde=$7 katetheme=$8 state=$9 niricolors=\${10} roficolors=\${11} yazitheme=\${12} zedtheme=\${13}
            status=0

            # tmp + mv: nobody reads a half-written file. .$$ because the shell of a
            # nested test session runs this at the same time.
            put() { printf '%s' "$2" > "$1.tmp.$$" && mv "$1.tmp.$$" "$1" || status=1; }

            # key=value in [section] of a KDE .ini (without kwriteconfig6).
            ini_set() {
                awk -v s="[$2]" -v k="$3" -v v="$4" '
                    $0 == s { insec = 1; print; next }
                    /^\\[/ { if (insec && !done) { print k "=" v; done = 1 } insec = 0 }
                    insec && index($0, k "=") == 1 { if (!done) print k "=" v; done = 1; next }
                    { print }
                    END { if (!done) { if (!insec) print "\\n" s; print k "=" v } }
                ' "$1" > "$1.tmp.$$" && mv "$1.tmp.$$" "$1" || status=1
            }

            # The user's own file, kept as <name>.before-spore (or with a number,
            # if that name is taken) before Spore's goes in its place.
            aside() {
                to=$1.before-spore
                n=2
                while [ -e "$to" ] || [ -L "$to" ]; do to=$1.before-spore-$n; n=$((n + 1)); done
                mv -- "$1" "$to" || status=1
            }

            # A file Spore writes in the user's config: a link someone else manages
            # (home-manager, the dotfiles) is left alone (false), and the user's
            # own file is set aside first. One of Spore's (its first line names it)
            # is simply rewritten.
            ours() {
                [ -L "$1" ] && return 1
                [ -e "$1" ] || return 0
                head -n 1 "$1" | grep -q spore || aside "$1"
                return 0
            }

            # GTK3 reads ~/.config/gtk-3.0/gtk.css only once, when the app starts,
            # and never re-reads it; what it does reload live is the theme when
            # gtk-theme changes. So the colors go in a theme of our own that imports
            # adw-gtk3(-dark), alternating between two names (spore-a/b) so the name
            # always changes, also when the palette changes and the mode doesn't.
            # The inactive one is written.
            key=/org/gnome/desktop/interface
            if [ "$(dconf read $key/gtk-theme)" = "'spore-a'" ]; then slot=spore-b; else slot=spore-a; fi
            base="/etc/profiles/per-user/$(id -un)/share/themes/$gtktheme/gtk-3.0/gtk.css"
            [ -f "$base" ] || { echo "theme not found: $base" >&2; status=1; }
            mkdir -p "$HOME/.local/share/themes/$slot/gtk-3.0"
            put "$HOME/.local/share/themes/$slot/gtk-3.0/gtk.css" "/* Generated by spore (shell/services/SystemTheme.qml): theme = $gtktheme + the palette's colors. */
@import url(\\"file://$base\\");
@import url(\\"file://$HOME/.config/gtk-3.0/thunar.css\\");
$gtkcss"
            # No colors here: it would be loaded once and cover the theme's.
            mkdir -p "$HOME/.config/gtk-3.0" && ours "$HOME/.config/gtk-3.0/gtk.css" && put "$HOME/.config/gtk-3.0/gtk.css" "/* Empty on purpose: the colors live in the spore-a/b theme (~/.local/share/themes), which GTK3 does reload live. See shell/services/SystemTheme.qml in the Spore repo. */
"
            # GTK4/libadwaita ignores gtk-theme and only reads this gtk.css at
            # startup: it picks up the palette when the app reopens.
            mkdir -p "$HOME/.config/gtk-4.0" && ours "$HOME/.config/gtk-4.0/gtk.css" && put "$HOME/.config/gtk-4.0/gtk.css" "$gtkcss"

            mkdir -p "$state"
            put "$state/kitty-dark.conf" "$kittydark"
            put "$state/kitty-light.conf" "$kittylight"
            # The user's niri config includes it with
            # include optional=true "~/.local/state/spore/niri.kdl";
            # niri re-reads it by itself when it changes.
            put "$state/niri.kdl" "$niricolors"
            # The rofi theme imports it (@import "~/.local/state/...").
            put "$state/rofi-colors.rasi" "$roficolors"
            put "$state/yazi-theme.toml" "$yazitheme"
            put "$state/zed-theme.json" "$zedtheme"

            # Links from each app's config to the generated files, only if the app
            # has a config folder (the user uses it), and never over a real file
            # the user put there or someone else's link (home-manager, the
            # dotfiles): only Spore's own (to its state, under this name or
            # my-shell's) are made again. Always made again: Zed watches
            # ~/.config/zed/themes, and rewriting a symlink's target isn't an event
            # in that folder (without this there was no hot reload).
            link() {
                [ -d "$(dirname "$2")" ] || return 0
                if [ -L "$2" ]; then
                    case $(readlink -- "$2") in "$state"/*|"\${state%/*}/my-shell"/*) ;; *) return 0 ;; esac
                elif [ -e "$2" ]; then
                    return 0
                fi
                ln -sfn "$1" "$2" || status=1
            }
            cfg="$HOME/.config"
            link "$state/kitty-dark.conf" "$cfg/kitty/dark-theme.auto.conf"
            link "$state/kitty-dark.conf" "$cfg/kitty/no-preference-theme.auto.conf"
            link "$state/kitty-light.conf" "$cfg/kitty/light-theme.auto.conf"
            link "$state/yazi-theme.toml" "$cfg/yazi/theme.toml"
            [ -d "$cfg/zed" ] && mkdir -p "$cfg/zed/themes"
            link "$state/zed-theme.json" "$cfg/zed/themes/spore.json"
            # On NixOS the kitty process is called .kitty-wrapped.
            pkill -USR1 -x .kitty-wrapped
            pkill -USR1 -x kitty

            # KDE's files are edited in place (only the colors, and two of Kate's
            # keys). The first time, a copy of each stays as <name>.before-spore;
            # a link is someone else's and isn't touched.
            kdeglobals="$HOME/.config/kdeglobals"
            if ! [ -L "$kdeglobals" ]; then
                if [ -s "$kdeglobals" ] && ! [ -e "$kdeglobals.before-spore" ]; then cp -p -- "$kdeglobals" "$kdeglobals.before-spore"; fi
                touch "$kdeglobals"
                { awk '/^\\[/ { skip = ($0 ~ /^\\[Colors:/) } !skip' "$kdeglobals"; printf '%s' "$kde"; } > "$kdeglobals.tmp.$$" \\
                    && mv "$kdeglobals.tmp.$$" "$kdeglobals" || status=1
            fi
            katerc="$HOME/.config/katerc"
            if [ -f "$katerc" ] && ! [ -L "$katerc" ]; then
                [ -e "$katerc.before-spore" ] || cp -p -- "$katerc" "$katerc.before-spore"
                ini_set "$katerc" "KTextEditor Renderer" "Auto Color Theme Selection" false
                ini_set "$katerc" "KTextEditor Renderer" "Color Theme" "$katetheme"
            fi

            dconf write $key/color-scheme "'$scheme'" &&
                dconf write $key/gtk-theme "'$slot'" &&
                dconf write $key/icon-theme "'$icons'" || status=1

            exit $status`

        stderr: StdioCollector {
            id: writerErr
        }

        onExited: (exitCode) => {
            if (exitCode !== 0)
                console.warn("SystemTheme: could not apply the theme to every app:", writerErr.text)
        }
    }
}
