#!/usr/bin/env node
// Generates shell/common/lucide.js with the Lucide icons (lucide.dev, ISC
// license) listed in tools/lucide-icons.txt (one name per line, # comments).
// It downloads each SVG from the official repo and turns everything into a
// single path (rect, circle, ellipse, line, polyline and polygon included),
// because Icon.qml draws paths with PathSvg. Usage: node tools/lucide.mjs
// Then restart the shell: hot reload doesn't re-read .js files
// (".pragma library" stays cached).
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const base = "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/"
// Brand logos (Simple Icons, CC0): listed as "simple:<name>". They're filled,
// not line icons: they also go in `filled`.
const simpleBase = "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/"

const names = readFileSync(join(root, "tools/lucide-icons.txt"), "utf8")
    .split("\n").map(l => l.replace(/#.*/, "").trim()).filter(Boolean)

const attrs = tag => Object.fromEntries([...tag.matchAll(/([\w-]+)="([^"]*)"/g)].map(m => [m[1], m[2]]))
const n = v => Number(v ?? 0)

// Separates the path's numbers with spaces. Above all the arc flags: SVG lets
// you write them run together ("a10 10 0 0010-10" = flags 0 and 0, x 10) and
// Qt's parser (PathSvg) doesn't understand that and draws the curve wrong.
function normalize(d) {
    const number = /^[-+]?(?:\d+\.?\d*|\.\d+)(?:e[-+]?\d+)?/i
    let out = "", cmd = "", arg = 0, i = 0
    while (i < d.length) {
        const c = d[i]
        if (/[\s,]/.test(c)) { i++; continue }
        if (/[a-df-z]/i.test(c)) { cmd = c; arg = 0; out += c; i++; continue }
        // In an arc, arguments 4 and 5 (out of 7) are single-digit flags.
        const flag = /a/i.test(cmd) && (arg % 7 === 3 || arg % 7 === 4)
        const tok = flag ? c : (d.slice(i).match(number) || [c])[0]
        out += (out && !/[a-z]$/i.test(out) ? " " : "") + tok
        i += tok.length
        arg++
    }
    return out
}

// An "m" at the start of a path is absolute, but joined to another path it
// would become relative: it's turned into "M". The pairs that follow it are
// relative lines ("m1 2 3 4" = "M1 2l3 4"), so they get an "l" in front.
function absoluteStart(d) {
    const m = d.trim().match(/^m\s*([-+]?[\d.]+(?:e[-+]?\d+)?)[\s,]*([-+]?[\d.]+(?:e[-+]?\d+)?)(.*)$/s)
    if (!m) return d.trim()
    const rest = m[3].trim()
    return `M${m[1]} ${m[2]}` + (/^[-+\d.]/.test(rest) ? "l" + rest : rest)
}

function toPath(el, a) {
    switch (el) {
    case "path": return absoluteStart(normalize(a.d))
    case "line": return `M${a.x1} ${a.y1}L${a.x2} ${a.y2}`
    case "polyline":
    case "polygon": {
        const p = a.points.trim().split(/[\s,]+/)
        let d = `M${p[0]} ${p[1]}`
        for (let i = 2; i < p.length; i += 2) d += `L${p[i]} ${p[i + 1]}`
        return el === "polygon" ? d + "z" : d
    }
    case "circle": {
        const [cx, cy, r] = [n(a.cx), n(a.cy), n(a.r)]
        return `M${cx - r} ${cy}a${r} ${r} 0 1 0 ${2 * r} 0a${r} ${r} 0 1 0 ${-2 * r} 0`
    }
    case "ellipse": {
        const [cx, cy, rx, ry] = [n(a.cx), n(a.cy), n(a.rx), n(a.ry)]
        return `M${cx - rx} ${cy}a${rx} ${ry} 0 1 0 ${2 * rx} 0a${rx} ${ry} 0 1 0 ${-2 * rx} 0`
    }
    case "rect": {
        const [x, y, w, h] = [n(a.x), n(a.y), n(a.width), n(a.height)]
        const r = Math.min(n(a.rx ?? a.ry), w / 2, h / 2)
        if (!r) return `M${x} ${y}h${w}v${h}h${-w}z`
        return `M${x + r} ${y}h${w - 2 * r}a${r} ${r} 0 0 1 ${r} ${r}v${h - 2 * r}a${r} ${r} 0 0 1 ${-r} ${r}`
            + `h${-(w - 2 * r)}a${r} ${r} 0 0 1 ${-r} ${-r}v${-(h - 2 * r)}a${r} ${r} 0 0 1 ${r} ${-r}z`
    }
    }
    throw new Error("elemento no soportado: " + el)
}

const out = {}
const filled = []
for (const entry of names) {
    const simple = entry.startsWith("simple:")
    const name = simple ? entry.slice(7) : entry
    const res = await fetch((simple ? simpleBase : base) + name + ".svg")
    if (!res.ok) {
        console.error(`✗ ${entry}: no existe (${res.status})`)
        process.exitCode = 1
        continue
    }
    const svg = await res.text()
    out[name] = [...svg.matchAll(/<(path|line|polyline|polygon|circle|ellipse|rect)\b([^>]*)\/?>/g)]
        .map(m => toPath(m[1], attrs(m[2]))).join("")
    if (simple) filled.push(name)
    console.log(`✓ ${name}`)
}

const body = Object.keys(out).sort()
    .map(k => `    ${JSON.stringify(k)}: ${JSON.stringify(out[k])}`).join(",\n")
writeFileSync(join(root, "shell/common/lucide.js"), `.pragma library

// Generated by tools/lucide.mjs from tools/lucide-icons.txt: don't edit by
// hand. Icons from Lucide (https://lucide.dev, ISC license) and logos from
// Simple Icons (https://simpleicons.org, CC0), on 24x24 grids. Icon.qml
// draws the Lucide ones with a stroke and the "filled" ones filled.
var paths = {
${body}
};

var filled = ${JSON.stringify(Object.fromEntries(filled.sort().map(k => [k, true])))};
`)
console.log("Done. Restart the shell to see the new icons (.js files aren't hot-reloaded).")
